VAGRANT_HOST_IP      : '192.168.33.10'
VAGRANT_HOST_NAME    : 'vagrant'
VAGRANT_BOX_NAME     : 'ubuntu-1404'
VAGRANT_BOX_MEMORY   : '4096'
VAGRANT_BOX_CORES    : '4'
VAGRANT_BASH_PROFILE : './etc/docker/images/base/conf/.bash_profile'
